cloud:
  greeting: "Hello!!"

---

spring:
  profiles: development
cloud:
  greeting: "Heelooooo development!!"


---


spring:
  profiles: sandbox
cloud:
  greeting: "Hello sandbox!!"


---


spring:
  profiles: production
cloud:
  greeting: "Hello production!!"

